"use client";

import { Activity, Clock3, Radio, RefreshCw, Wifi } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { calculatePlayerMetrics, calculateTeamMetrics, formatMetric } from "@/lib/stats/engine";
import type { MatchBoxscore } from "@/lib/stats/types";

function LiveMetric({ label, value, copy }: { label: string; value: string; copy: string }) {
  return <article className="border border-stone-200 bg-white p-4"><div className="text-xs font-black uppercase tracking-[0.1em] text-stone-500">{label}</div><div className="mt-2 font-condensed text-3xl font-black tabular-nums">{value}</div><p className="mt-1 text-[11px] text-stone-400">{copy}</p></article>;
}

export function LiveMatchPanel({ matches, onOpenMatch }: { matches: MatchBoxscore[]; onOpenMatch: (match: MatchBoxscore) => void }) {
  const liveMatch = matches.find((match) => match.liveStatus === "live") ?? matches[0];
  if (!liveMatch) return <section className="panel p-6"><div className="grid min-h-80 place-items-center text-center"><div className="max-w-xl"><div className="mx-auto grid size-14 place-items-center bg-stone-950 text-white"><Radio className="size-6" /></div><h2 className="mt-5 text-2xl font-black">Aucun match live actuellement</h2><p className="mt-3 text-sm leading-6 text-stone-500">Lorsqu’un connecteur Synergy ou Sportradar alimentera Supabase, le score, les quart-temps et les statistiques avancées apparaîtront ici avec un rafraîchissement toutes les 10 secondes.</p><div className="mt-5 flex flex-wrap justify-center gap-2"><span className="watch-chip"><Wifi className="size-3.5" /> Synergy à connecter</span><span className="watch-chip"><Wifi className="size-3.5" /> Sportradar à connecter</span></div></div></div></section>;

  const metrics = calculateTeamMetrics(liveMatch);
  const players = calculatePlayerMetrics(liveMatch).filter((player) => player.minutesDecimal > 0).sort((a, b) => b.points - a.points);
  const updatedAt = liveMatch.lastSyncedAt ? new Date(liveMatch.lastSyncedAt).toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit", second: "2-digit" }) : "en attente du fournisseur";

  return <div className="space-y-5">
    <section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-4 bg-stone-950 p-5 text-white sm:p-6"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[0.14em] text-red-400"><span className="size-2 animate-pulse rounded-full bg-red-500" />{liveMatch.liveStatus === "live" ? "En direct" : "Match programmé"}</div><h2 className="mt-2 text-2xl font-black">{liveMatch.team.name} – {liveMatch.opponent.name}</h2><p className="mt-1 text-xs text-stone-400">{liveMatch.competition} · source {liveMatch.provider ?? "live"}</p></div><div className="flex items-center gap-5"><span className="font-condensed text-5xl font-black tabular-nums">{liveMatch.team.points}</span><span className="text-stone-600">—</span><span className="font-condensed text-5xl font-black tabular-nums">{liveMatch.opponent.points}</span></div></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-stone-800 bg-stone-900 px-5 py-3 text-xs text-stone-300"><span className="flex items-center gap-2"><RefreshCw className="size-3.5" /> Actualisation automatique toutes les 10 secondes</span><span className="flex items-center gap-2"><Clock3 className="size-3.5" /> Dernière donnée : {updatedAt}</span></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><LiveMetric label="ORtg" value={formatMetric(metrics.ortg)} copy="pour 100 possessions" /><LiveMetric label="DRtg" value={formatMetric(metrics.drtg)} copy="pour 100 possessions" /><LiveMetric label="Net" value={`${metrics.net > 0 ? "+" : ""}${formatMetric(metrics.net)}`} copy="différentiel estimé" /><LiveMetric label="eFG%" value={`${formatMetric(metrics.efg)}%`} copy="efficacité de tir" /><LiveMetric label="TOV%" value={`${formatMetric(metrics.tov)}%`} copy="pertes de balle" /><LiveMetric label="ORB%" value={`${formatMetric(metrics.orb)}%`} copy="rebond offensif" /></section>

    <section className="grid gap-5 lg:grid-cols-2"><article className="panel p-5"><div className="flex items-center gap-2"><Activity className="size-5 text-[#d71920]" /><div><p className="eyebrow">Progression du score</p><h3 className="mt-1 text-xl font-black">Quart-temps</h3></div></div><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={liveMatch.quarters}><CartesianGrid stroke="#e7e3db" vertical={false} /><XAxis dataKey="label" axisLine={false} tickLine={false} fontSize={11} /><YAxis axisLine={false} tickLine={false} fontSize={11} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="team" name={liveMatch.team.name} fill="#d71920" /><Bar dataKey="opponent" name={liveMatch.opponent.name} fill="#292524" /></BarChart></ResponsiveContainer></div></article><article className="panel p-5"><p className="eyebrow">Après le buzzer</p><h3 className="mt-1 text-xl font-black">Archivage automatique</h3><div className="mt-5 space-y-3 text-sm leading-6 text-stone-600"><p>Lorsque le fournisseur passe le match au statut <strong className="text-stone-950">final</strong>, il disparaît de cette vue live.</p><p>Il reste accessible dans <strong className="text-stone-950">Match JL</strong> et entre automatiquement dans les calculs de la section <strong className="text-stone-950">Historique</strong>.</p></div><Button onClick={() => onOpenMatch(liveMatch)} className="mt-6 rounded-none bg-stone-950 hover:bg-[#d71920]">Ouvrir l’analyse complète</Button></article></section>

    <section className="panel overflow-hidden"><div className="border-b border-stone-200 p-5"><p className="eyebrow">Rotation live</p><h3 className="mt-1 text-xl font-black">Joueurs</h3></div><div className="overflow-x-auto"><Table className="min-w-[900px]"><TableHeader><TableRow className="bg-stone-50"><TableHead>Joueur</TableHead>{["MIN", "PTS", "REB", "AST", "TS%", "USG%", "TOV%", "+/−"].map((label) => <TableHead key={label} className="text-right">{label}</TableHead>)}</TableRow></TableHeader><TableBody>{players.map((player) => <TableRow key={player.id}><TableCell className="font-bold">{player.name}</TableCell><TableCell className="text-right">{player.minutes}</TableCell><TableCell className="text-right font-bold">{player.points}</TableCell><TableCell className="text-right">{player.orb + player.drb}</TableCell><TableCell className="text-right">{player.ast}</TableCell><TableCell className="text-right">{formatMetric(player.ts)}</TableCell><TableCell className="text-right">{formatMetric(player.usg)}</TableCell><TableCell className="text-right">{formatMetric(player.tovPct)}</TableCell><TableCell className="text-right">{player.plusMinus > 0 ? "+" : ""}{player.plusMinus}</TableCell></TableRow>)}</TableBody></Table></div></section>
  </div>;
}
